# Generated by Django 4.2.4 on 2023-09-20 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer_Family_Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(blank=True, default="", max_length=500)),
                ("relation", models.CharField(blank=True, default="", max_length=500)),
                ("age", models.CharField(blank=True, default="", max_length=500)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_health_state",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "customer_any_prescription",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("customer_had_full_body_check_up", models.BooleanField(default=False)),
                (
                    "customer_suffered_any_disease",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("customer_smoke_alcohol", models.BooleanField(default=False)),
                (
                    "customer_thought_about_workout",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "customer_activity_level",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "customer_any_symptoms",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "customer_lifestyle",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("note", models.CharField(blank=True, default="", max_length=5000)),
                (
                    "customer_family_disease",
                    models.ManyToManyField(
                        blank=True, default="", to="inquiry.customer_family_disease"
                    ),
                ),
                (
                    "customer_name",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.customer",
                    ),
                ),
            ],
        ),
    ]
