# Generated by Django 4.2.4 on 2023-09-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0002_alter_inquiry_customer_smoke_alcohol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="customer_had_full_body_check_up",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
