# Generated by Django 4.2.4 on 2023-09-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0003_alter_inquiry_customer_had_full_body_check_up"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="inquiry_status",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
