# Generated by Django 4.2.4 on 2023-09-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0004_inquiry_inquiry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="trash",
            field=models.BooleanField(default=False),
        ),
    ]
