# Generated by Django 4.2.4 on 2023-10-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0006_alter_inquiry_customer_lifestyle"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="inquiry_source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
