# Generated by Django 4.2.4 on 2023-10-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0007_inquiry_inquiry_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="inquiry_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
