# Generated by Django 4.2.4 on 2024-06-29 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0007_alter_diet_plan_package_package_validity_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('monthly_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.CharField(blank=True, default='', max_length=5000)),
                ('received_amount', models.CharField(blank=True, default='', max_length=5000)),
                ('due_amount', models.CharField(blank=True, default='', max_length=5000)),
                ('receipt_bill_no', models.CharField(blank=True, default='', max_length=5000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
