# Generated by Django 4.2.4 on 2024-07-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0002_employee_trashed'),
        ('account', '0002_account_account_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_created_by', to='humanresource.employee'),
        ),
    ]
