# Generated by Django 4.2.4 on 2024-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_account_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_reference',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='due_amount',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='receipt_bill_no',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='received_amount',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_amount',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
