# Generated by Django 4.2.4 on 2024-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_account_reference_alter_account_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='entry_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
