# Generated by Django 4.2.4 on 2024-07-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_logbook_trashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
