# Generated by Django 4.2.4 on 2024-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_logbook_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodycomposition',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
