# Generated by Django 4.2.4 on 2024-07-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_dietplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='dinner_rice_dhindo_select',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Dhindo', 'Dhindo'), ('Chakla', 'Chakla')], default='rice', max_length=100),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='dinner_rice_dhindo',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
