# Generated by Django 4.2.4 on 2024-07-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_dietplan_dinner_rice_dhindo_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='afternoon_snack_time',
            field=models.CharField(default='4:30 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='dinner_time',
            field=models.CharField(default='8:30 AM', max_length=100),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='lunch_time',
            field=models.CharField(default='12:30 PM', max_length=100),
        ),
    ]
