# Generated by Django 4.2.4 on 2024-07-06 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0012_alter_dietplan_created_by_alter_dietplan_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
