# Generated by Django 4.2.4 on 2024-12-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0013_dietplan_approved_by_dietplan_trashed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='day',
            field=models.CharField(choices=[('Everyday', 'Everyday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='EveryDay', max_length=100),
        ),
    ]
