# Generated by Django 4.2.4 on 2024-12-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0014_alter_dietplan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
