# Generated by Django 4.2.4 on 2023-08-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "left_date",
                    models.DateField(auto_created=True, blank=True, null=True),
                ),
                ("join_date", models.DateField(auto_created=True, null=True)),
                (
                    "employee_id",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "date_of_birth",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Date of birth (Y-M-D) ",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                            ("", "Default"),
                        ],
                        default="",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "marital",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Legal Cohabitant", "Legal Cohabitant"),
                            ("Widower", "Widower"),
                            ("Divorced", "Divorced"),
                            ("", "Default"),
                        ],
                        default="",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "citizen_number",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "pan_number",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "employee_note",
                    models.CharField(blank=True, default="", max_length=256, null=True),
                ),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "contact",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "work_phone_number",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "work_email",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "guardian_name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "guardian_relation",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "guardian_address",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "guardian_phone_number",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "job_position",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                ("fired", models.BooleanField(default=False)),
                (
                    "branch",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "grade",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "ratings",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                ("stay_in_quarters", models.BooleanField(default=False)),
                (
                    "employee_type",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "outsource_company",
                    models.CharField(blank=True, default="", max_length=225, null=True),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, default="", max_length=3000, null=True
                    ),
                ),
                (
                    "terms_and_condition",
                    models.CharField(
                        blank=True, default="", max_length=3000, null=True
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="humanresource.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_salary",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "room_allowance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "food_allowance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "overtime_allowance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("intensive", models.CharField(blank=True, default="", max_length=100)),
                (
                    "festival_bonus",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "other_allowance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "provident_fund",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[("Cash", "Cash"), ("Bank", "Bank"), ("", "Default")],
                        default="",
                        max_length=100,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "bank_branch",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "bank_account_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "bank_account_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tax_payer_employee", models.BooleanField(default=False)),
                ("tax_rate", models.CharField(blank=True, default="", max_length=100)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="humanresource.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaySlip_Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ps_code", models.CharField(blank=True, default="", max_length=100)),
                (
                    "period_date",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "generated_date",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="humanresource.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(blank=True, default="", max_length=100)),
                (
                    "salary_period_from",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "salary_period_to",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "basic_salary",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "room_allowance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "food_allowance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("overtime", models.CharField(blank=True, default="", max_length=100)),
                ("intensive", models.CharField(blank=True, default="", max_length=100)),
                (
                    "festival_bonus",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "other_allowance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "provident_fund",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "total_salary",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("advance", models.CharField(blank=True, default="", max_length=100)),
                (
                    "provident_fund_deduction",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "room_benefit",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "social_security_tax",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "medical_loan_installment",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "leave_amount",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "total_deduction",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "net_salary_payable",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "payroll_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "verification_status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("finished", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("saved", "saved"),
                            ("submited", "submited"),
                            ("approved", "approved"),
                            ("canceled", "canceled"),
                        ],
                        default="saved",
                        max_length=25,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="humanresource.employee",
                    ),
                ),
                (
                    "payslip_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="humanresource.playslip_code",
                    ),
                ),
            ],
        ),
    ]
