# Generated by Django 4.2.4 on 2023-08-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diet_plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=555, unique=True)),
                ("price", models.CharField(max_length=555, unique=True)),
                ("time", models.CharField(max_length=555, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, default="", max_length=100)),
                ("name", models.CharField(blank=True, default="", max_length=500)),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("address", models.CharField(blank=True, default="", max_length=100)),
                ("landmark", models.CharField(blank=True, default="", max_length=100)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("email", models.CharField(blank=True, default="", max_length=500)),
                ("website", models.CharField(blank=True, default="", max_length=100)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("pan_no", models.CharField(blank=True, default="", max_length=100)),
                ("tag", models.CharField(blank=True, default="", max_length=100)),
                (
                    "diet_plan",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.diet_plan",
                    ),
                ),
            ],
        ),
    ]
