# Generated by Django 4.2.4 on 2023-08-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diet_Plan_Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=555, unique=True)),
                ("package_cost", models.CharField(max_length=555, unique=True)),
                ("package_service", models.CharField(max_length=555, unique=True)),
                ("package_visibility", models.BooleanField(default=True)),
                ("package_validity", models.BooleanField(default=True)),
                (
                    "package_validity_time",
                    models.CharField(max_length=555, unique=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="customer", old_name="pan_no", new_name="age",
        ),
        migrations.RenameField(
            model_name="customer", old_name="organization", new_name="annual_income",
        ),
        migrations.RenameField(
            model_name="customer", old_name="type", new_name="date_of_birth",
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_number",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="profession",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="social_number",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="Customer_Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.CharField(blank=True, default="", max_length=100)),
                ("height", models.CharField(blank=True, default="", max_length=100)),
                ("bmi", models.CharField(blank=True, default="", max_length=100)),
                ("whr", models.CharField(blank=True, default="", max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.customer",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="customer",
            name="diet_plan",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="customer.diet_plan_package",
            ),
        ),
        migrations.DeleteModel(name="Diet_plan",),
    ]
