# Generated by Django 4.2.4 on 2023-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_customer_diet_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer_stats",
            name="hip",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customer_stats",
            name="waist",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
