# Generated by Django 4.2.4 on 2023-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_customer_stats_hip_customer_stats_waist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer_stats",
            name="bmi",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer_stats",
            name="height",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer_stats",
            name="hip",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer_stats",
            name="waist",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer_stats",
            name="weight",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer_stats",
            name="whr",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
