# Generated by Django 4.2.4 on 2023-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer",
            "0005_alter_customer_stats_bmi_alter_customer_stats_height_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer_stats",
            name="bmi",
            field=models.FloatField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer_stats",
            name="whr",
            field=models.FloatField(blank=True, default="", max_length=100, null=True),
        ),
    ]
