# Generated by Django 4.2.4 on 2024-07-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_stats',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
