# Generated by Django 4.2.4 on 2024-07-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_stats_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_stats',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
