# Generated by Django 4.2.4 on 2024-07-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
