# Generated by Django 4.2.4 on 2023-10-26 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0006_alter_customer_stats_bmi_alter_customer_stats_whr"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trash", models.BooleanField(default=False)),
                (
                    "registration_status",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "total_amount",
                    models.CharField(blank=True, default="", max_length=5000),
                ),
                (
                    "received_amount",
                    models.CharField(blank=True, default="", max_length=5000),
                ),
                (
                    "due_amount",
                    models.CharField(blank=True, default="", max_length=5000),
                ),
                (
                    "receipt_bill_no",
                    models.CharField(blank=True, default="", max_length=5000),
                ),
                ("note", models.CharField(blank=True, default="", max_length=5000)),
                (
                    "account_by",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="account_by",
                        to="customer.customer",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="customer",
                        to="customer.customer",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="employee",
                        to="customer.customer",
                    ),
                ),
            ],
        ),
    ]
