# Generated by Django 4.2.4 on 2023-10-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0007_inquiry_inquiry_source"),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="inquiry",
                to="inquiry.inquiry",
            ),
        ),
    ]
