# Generated by Django 4.2.4 on 2023-10-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0001_initial"),
        ("customer", "0006_alter_customer_stats_bmi_alter_customer_stats_whr"),
        ("inquiry", "0008_inquiry_inquiry_id"),
        ("registration", "0003_registration_registration_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="account_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="account_by",
                to="humanresource.employee",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="customer",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="employee",
                to="humanresource.employee",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="inquiry",
                to="inquiry.inquiry",
            ),
        ),
    ]
