# Generated by Django 4.2.4 on 2023-10-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_alter_registration_account_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="registration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
