# Generated by Django 4.2.4 on 2023-10-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_registration_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="registration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
