# Generated by Django 4.2.4 on 2023-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_alter_registration_registration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="gym_package_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="gym_package_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="package_booked",
            field=models.CharField(blank=True, default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="registration",
            name="package_cost",
            field=models.CharField(blank=True, default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="registration",
            name="package_service",
            field=models.CharField(blank=True, default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="registration",
            name="therapy_package_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="therapy_package_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
