# Generated by Django 4.2.4 on 2023-10-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_registration_gym_package_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="gym_package_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="gym_package_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="therapy_package_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="therapy_package_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
