# Generated by Django 4.2.4 on 2023-10-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_alter_registration_gym_package_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="discount_amount",
            field=models.CharField(blank=True, default="", max_length=5000),
        ),
    ]
